---
apiVersion: v1
kind: Service # Pod-to-pod communication kosam.
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  clusterIP: None #HEADLESS SERVICE FOR STATEFUL SET
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container port
---
apiVersion: v1
kind: Service #Applications mongodb ni access cheyyadaniki.
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:  #StatefulSet manage cheyyalsina pods labels.
      component: mongodb
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "mongodb-headless" # this should be headless service
  replicas: 3 # by default is 1
  template:  #Pods ela create avvalo define chestham.
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mongodb
        image: venkattholeti/mongodb:v1
        volumeMounts:  #MongoDB data ekkada store cheyyalo chepthundi.
        - name: mongodb-data
          mountPath: /data/db
  # This is nothing but PVC, you can directly create here
  volumeClaimTemplates:  #Each pod ki separate PVC create chesthundi.
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi

------------------------------------


    #             mongodb service
    #                    |
    #      ----------------------------
    #      |            |             |
    #  mongodb-0    mongodb-1    mongodb-2
    #      |            |             |
    #    PVC          PVC           PVC