apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: app
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  # deployment labels
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector: 
    matchLabels: #Deployment ye pods ni manage cheyyalo identify chesthundi.
      component: catalogue
      project: roboshop
      tier: app
  # This is pod definition
  template: #Pods ela create avvali? ani define chestham.
    metadata:
      labels: #Must match selector labels.Lekapothe deployment pods ni identify cheyyaledu.
        component: catalogue
        project: roboshop
        tier: app
    spec: #POD SPEC, ACTUAL POD DETAILS
      containers:
      - name: catalogue
        image: venkattholeti/catalogue:v1
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        envFrom:
        - configMapRef: #ConfigMap values ni container env vars ga inject chesthundi.
            name: catalogue
---
apiVersion: v1
kind: Service #Catalogue app ni expose cheyyadaniki.
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:  
  selector: # Catalogue pods ni select chesthundi.
    component: catalogue
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port

# Apps direct pod IP use cheyyavu.Because pods recreate ayithe IP change avthundi.Service stable endpoint istundi.
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue
  namespace: roboshop
spec:
  scaleTargetRef: #Which deployment ni scale cheyyalo.
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue
  minReplicas: 1
  maxReplicas: 10
  metrics: #Scaling base enti?
  - type: Resource
    resource:
      name: cpu #CPU usage base cheskoni scale chesthundi.
      target:
        type: Utilization
        averageUtilization: 10